### ISSUE TITLE
local development error

### ISSUE THREAD

**Issue by ser1us** [netlify/remix-edge-template#25]
Hello!

I am running into an exception when I try to run the example locally.

I have set-up this repository using the deploy now button. All but local development works well. After cloning and following the readme.md file I am at the point where the dev server is spinning up. Unfortunately I am greeted with the following error:

```
💿 Built in 359ms
TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at relative (node:path:498:5)
    at C:\Users\chris\AppData\Local\pnpm\global\5\.pnpm\netlify-cli@10.3.3\node_modules\netlify-cli\src\lib\edge-functions\proxy.js:103:11
    at Set.forEach (<anonymous>)
    at C:\Users\chris\AppData\Local\pnpm\global\5\.pnpm\netlify-cli@10.3.3\node_modules\netlify-cli\src\lib\edge-functions\proxy.js:96:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async onRequest (C:\Users\chris\AppData\Local\pnpm\global\5\.pnpm\netlify-cli@10.3.3\node_modules\netlify-cli\src\utils\proxy.js:413:33) {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at relative (node:path:498:5)
    at C:\Users\chris\AppData\Local\pnpm\global\5\.pnpm\netlify-cli@10.3.3\node_modules\netlify-cli\src\lib\edge-functions\proxy.js:103:11
    at Set.forEach (<anonymous>)
    at C:\Users\chris\AppData\Local\pnpm\global\5\.pnpm\netlify-cli@10.3.3\node_modules\netlify-cli\src\lib\edge-functions\proxy.js:96:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async onRequest (C:\Users\chris\AppData\Local\pnpm\global\5\.pnpm\netlify-cli@10.3.3\node_modules\netlify-cli\src\utils\proxy.js:413:33) {
  code: 'ERR_INVALID_ARG_TYPE'
}

C:\Users\chris\AppData\Local\pnpm\global\5\.pnpm\netlify-redirector@0.2.1\node_modules\netlify-redirector\lib\redirects.js:116
      throw ex;
      ^
abort({"code":"ERR_INVALID_ARG_TYPE"}) at Error
    at jsStackTrace (C:\Users\chris\AppData\Local\pnpm\global\5\.pnpm\netlify-redirector@0.2.1\node_modules\netlify-redirector\lib\redirects.js:1070:13)
    at stackTrace (C:\Users\chris\AppData\Local\pnpm\global\5\.pnpm\netlify-redirector@0.2.1\node_modules\netlify-redirector\lib\redirects.js:1087:12)
    at process.abort (C:\Users\chris\AppData\Local\pnpm\global\5\.pnpm\netlify-redirector@0.2.1\node_modules\netlify-redirector\lib\redirects.js:8502:44)
    at process.emit (node:events:527:28)
    at processEmit [as emit] (C:\Users\chris\AppData\Local\pnpm\global\5\.pnpm\signal-exit@3.0.7\node_modules\signal-exit\index.js:199:34)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

OS: Windows 11
Package Manager: PNPM (7.1.6) / NPM (8.5.5) same result
Node: v16.15.0

Not sure if this is a Windows only issue? Appreciate any help :) 

Cheers,
Christoph

**Comment by nickytonline** [comment]
I'm going to go ahead and close this as the official template will be coming soon. It's based off of work in https://github.com/netlify/remix-compute/pull/16 and https://github.com/netlify/remix-edge-template/pull/83
