### ISSUE TITLE
Does not deploy

### ISSUE THREAD

**Issue by tylermercer** [netlify/remix-edge-template#6]
I can't seem to get this template working. I tried clicking the "Deploy to Netlify" button, then downloading the files manually, and then using `npx create-remix --template netlify/remix-edge-template` as specified [here](https://docs.netlify.com/integrations/frameworks/remix/#edge-functions). None of those approaches worked; the project fails to build both locally and on Netlify. I even tried installing the missing `@remix-run/netlify-edge` package (which is referenced in the project but not found in the package.json) and updating the React packages as was done in PR #4, but it gave me the same error.

The error seems to be with the Edge Functions deployment. This is the error in the deployment console:
```
...
────────────────────────────────────────────────────────────────
9:02:51 PM:   2. Edge Functions bundling                                    
9:02:51 PM: ────────────────────────────────────────────────────────────────
9:02:51 PM: ​
9:02:51 PM: Packaging Edge Functions from .netlify/edge-functions directory:
9:02:51 PM:  - server
9:03:03 PM: error: TS2300 [ERROR]: Duplicate identifier 'LibraryManagedAttributes'.
9:03:03 PM:         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
9:03:03 PM:              ~~~~~~~~~~~~~~~~~~~~~~~~
9:03:03 PM:     at https://cdn.esm.sh/v77/@types/react@18.0.1/index.d.ts:3103:14
9:03:03 PM:     'LibraryManagedAttributes' was also declared here.
9:03:03 PM:             type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
9:03:03 PM:                  ~~~~~~~~~~~~~~~~~~~~~~~~
9:03:03 PM:         at https://cdn.esm.sh/v77/@types/react@18.0.5/index.d.ts:3123:14
9:03:03 PM: TS2300 [ERROR]: Duplicate identifier 'LibraryManagedAttributes'.
9:03:03 PM:         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
9:03:03 PM:              ~~~~~~~~~~~~~~~~~~~~~~~~
9:03:03 PM:     at https://cdn.esm.sh/v77/@types/react@18.0.5/index.d.ts:3123:14
9:03:03 PM:     'LibraryManagedAttributes' was also declared here.
9:03:03 PM:             type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
9:03:03 PM:                  ~~~~~~~~~~~~~~~~~~~~~~~~
9:03:03 PM:         at https://cdn.esm.sh/v77/@types/react@18.0.1/index.d.ts:3103:14
9:03:03 PM: Found 2 errors.
9:03:03 PM: ​
9:03:03 PM: ────────────────────────────────────────────────────────────────
9:03:03 PM:   Bundling of Function "undefined" failed                       
9:03:03 PM: ────────────────────────────────────────────────────────────────
9:03:03 PM: ​
9:03:03 PM:   Error message
9:03:03 PM:   Command failed with exit code 1: /opt/build/repo/.netlify/plugins/deno-cli/deno bundle --import-map=data:application/json;base64,eyJpbXBvcnRzIjp7IkByZW1peC1ydW4vbmV0bGlmeS1lZGdlIjoiZmlsZTovLy9vcHQvYnVpbGQvcmVwby9ub2RlX21vZHVsZXMvQHJlbWl4LXJ1bi9uZXRsaWZ5LWVkZ2UvbW9kLnRzIiwiQHJlbWl4LXJ1bi9kZXYvc2VydmVyLWJ1aWxkIjoiZmlsZTovLy9vcHQvYnVpbGQvcmVwby9ub2RlX21vZHVsZXMvQHJlbWl4LXJ1bi9kZXYvc2VydmVyLWJ1aWxkLmQudHMiLCJAcmVtaXgtcnVuL3NlcnZlci1ydW50aW1lIjoiaHR0cHM6Ly9lc20uc2gvQHJlbWl4LXJ1bi9zZXJ2ZXItcnVudGltZUAxLjQuMT9waW49djc3IiwibmV0bGlmeTplZGdlIjoiaHR0cHM6Ly9lZGdlLWJvb3RzdHJhcC5uZXRsaWZ5LmFwcC92MS9pbmRleC50cyJ9fQ== --quiet /tmp/edge-625f77bc71fe220008c3d6e4/85737d9a-5f2f-46d5-aa46-00d9a6a97762-pre.js /tmp/edge-625f77bc71fe220008c3d6e4/85737d9a-5f2f-46d5-aa46-00d9a6a97762.js (https://ntl.fyi/exit-code-1)
9:03:03 PM:   error: TS2300 [ERROR]: Duplicate identifier 'LibraryManagedAttributes'.
9:03:03 PM:           type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
9:03:03 PM:                ~~~~~~~~~~~~~~~~~~~~~~~~
9:03:03 PM:       at https://cdn.esm.sh/v77/@types/react@18.0.1/index.d.ts:3103:14
9:03:03 PM: ​
9:03:03 PM:       'LibraryManagedAttributes' was also declared here.
9:03:03 PM:               type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
9:03:03 PM:                    ~~~~~~~~~~~~~~~~~~~~~~~~
9:03:03 PM:           at https://cdn.esm.sh/v77/@types/react@18.0.5/index.d.ts:3123:14
9:03:03 PM: ​
9:03:03 PM:   TS2300 [ERROR]: Duplicate identifier 'LibraryManagedAttributes'.
9:03:03 PM:           type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
9:03:03 PM:                ~~~~~~~~~~~~~~~~~~~~~~~~
9:03:03 PM:       at https://cdn.esm.sh/v77/@types/react@18.0.5/index.d.ts:3123:14
9:03:03 PM: ​
9:03:03 PM:       'LibraryManagedAttributes' was also declared here.
9:03:03 PM:               type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
9:03:03 PM:                    ~~~~~~~~~~~~~~~~~~~~~~~~
9:03:03 PM:           at https://cdn.esm.sh/v77/@types/react@18.0.1/index.d.ts:3103:14
9:03:03 PM: ​
9:03:03 PM:   Found 2 errors.
9:03:03 PM: ​
9:03:03 PM:   Error location
9:03:03 PM:   While bundling Function "undefined"
9:03:03 PM: ​
9:03:03 PM:   Resolved config
9:03:03 PM:   build:
9:03:03 PM:     command: yarn build
9:03:03 PM:     commandOrigin: config
9:03:03 PM:     publish: /opt/build/repo/public
9:03:03 PM:     publishOrigin: config
9:03:03 PM:   headers:
9:03:03 PM:     - for: /build/*
      values:
        Cache-Control: public, max-age=31536000, s-maxage=31536000
  headersOrigin: config
Caching artifacts
...
```

**Comment by tylermercer** [comment]
Duplicate of #5. Not sure why I didn't see that before.
