### ISSUE TITLE
npm run dev doesn't work

### ISSUE THREAD

**Issue by ticup** [netlify/remix-edge-template#68]
Using a fresh clone of this repository `npm run dev` doesn't work.
When going to the server's endpoint I get

````
.netlify/edge-functions/server.js:15626
export {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at node_modules/@remix-run/serve/index.js:43:17
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
````

Not using remix CLI, but using netlify CLI, it does work though: `npm run start`

**Comment by nickytonline** [comment]
I'm going to go ahead and close this as the official template will be coming soon. It's based off of work in https://github.com/netlify/remix-compute/pull/16.
